import {
  Activity,
  ArrowDown,
  ArrowUp,
  ArrowUpRight,
  Box,
  Cable,
  CircleDot,
  CloudRain,
  Contrast,
  Copy,
  Download,
  Droplet,
  Droplets,
  Ellipsis,
  Eraser,
  EyeOff,
  FileCode,
  Gauge,
  GripVertical,
  History,
  Keyboard,
  Layers,
  Leaf,
  Link2,
  ListChecks,
  ListFilter,
  LogIn,
  LogOut,
  Maximize2,
  Menu,
  Minimize2,
  Monitor,
  PanelLeftClose,
  PanelLeftOpen,
  Power,
  Presentation,
  Radar,
  RotateCcw,
  Ruler,
  Save,
  Search,
  SlidersHorizontal,
  Sprout,
  Square,
  Stethoscope,
  Sun,
  SunMoon,
  Thermometer,
  Undo2,
  Unlink2,
  Upload,
  Usb,
  Wrench,
  ZoomIn,
  ZoomOut,
} from "lucide-react";

/**
 * Glifos de laboratorio que la iconografía de Telemática USM no trae. Comparten grilla 24,
 * trazo 2 y extremos redondeados, así que conviven con los íconos propios como una sola
 * familia. Las pantallas nunca importan lucide directamente: usan <Icon name="…" />.
 */
export const extraIcons = {
  activity: Activity,
  arrowDown: ArrowDown,
  arrowUp: ArrowUp,
  arrowUpRight: ArrowUpRight,
  cable: Cable,
  collapse: Minimize2,
  contrast: Contrast,
  copy: Copy,
  cube: Box,
  dot: CircleDot,
  download: Download,
  drop: Droplet,
  drops: Droplets,
  eraser: Eraser,
  expand: Maximize2,
  eyeOff: EyeOff,
  fileCode: FileCode,
  filter: ListFilter,
  gauge: Gauge,
  grip: GripVertical,
  history: History,
  keyboard: Keyboard,
  layers: Layers,
  leaf: Leaf,
  link: Link2,
  listChecks: ListChecks,
  login: LogIn,
  logout: LogOut,
  menu: Menu,
  monitor: Monitor,
  more: Ellipsis,
  panelClose: PanelLeftClose,
  panelOpen: PanelLeftOpen,
  power: Power,
  projector: Presentation,
  radar: Radar,
  rain: CloudRain,
  rotate: RotateCcw,
  ruler: Ruler,
  save: Save,
  search: Search,
  sliders: SlidersHorizontal,
  sprout: Sprout,
  stethoscope: Stethoscope,
  stop: Square,
  sun: Sun,
  themeAuto: SunMoon,
  thermometer: Thermometer,
  undo: Undo2,
  unlink: Unlink2,
  upload: Upload,
  usb: Usb,
  wrench: Wrench,
  zoomIn: ZoomIn,
  zoomOut: ZoomOut,
} as const;

export type ExtraIconName = keyof typeof extraIcons;
